# This should not be modified in the usual case.
fullnameOverride: juicefs

##
## Example:
##   - key: "toleration=key"
##     operator: "Equal"
##     value: "value"
##     effect: "NoSchedule"
##
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

tieredstore:
  path: /dev/shm

## WORKER ##
worker:
  image: juicedata/juicefs-csi-driver
  imageTag: v0.10.5
  imagePullPolicy: IfNotPresent
  nodeSelector: {}
  cacheDir: ""
  resources:
    requests:
#      cpu: "0.5"
#      memory: "1G"
    limits:
#      cpu: "4"
#      memory: "4G"


## FUSE ##

fuse:
  format:
    enable: true
    nameSecret: jfs-secret
    accesskeySecret: jfs-secret
    secretkeySecret: jfs-secret
    bucketSecret: jfs-secret
    metaurlSecret: jfs-secret
    storageSecret: jfs-secret
  criticalPod: false
  enabled: true
  image: juicedata/juicefs-csi-driver
  imageTag: v0.10.5
  imagePullPolicy: IfNotPresent
  nodeSelector: {}
  dnsPolicy: ClusterFirstWithHostNet
  # Mount path in the host
  mountPath: /mnt/jfs
  hostMountPath: /mnt/jfs
  command: "/usr/local/bin/juicefs mount /mnt/jfs"
  statCmd: "stat -c %i /mnt/jfs"
  resources:
    requests:
#      cpu: "0.5"
#      memory: "1G"
    limits:
#      cpu: "4"
#      memory: "4G"
